include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/assets/**
    - tools/bricks/**/__brick__/**
    - bricks/**/__brick__/**
