name: everlook_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  adaptive_theme: ^3.6.0
  analytics: ^2.0.3
  auto_route: ^7.8.4
  cached_network_image: ^3.4.1
  collection: 1.18.0
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  elementary: ^3.1.1
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_easy_dialogs: ^4.0.1
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: 2.0.9
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  fresh_dio: 0.4.1
  image_picker: ^1.1.2
  intl: 0.19.0
  json_annotation: ^4.9.0
  logger: 1.4.0
  mask_text_input_formatter: 2.9.0
  mason: ^0.1.0-dev.60
  nested: 1.0.0
  path: 1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  restart_app: ^1.3.2
  retrofit: ^4.4.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  shimmer: 3.0.0
  surf_logger: ^2.0.2
  surf_widget_test_composer: ^0.0.6
  union_state: ^0.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  elementary_test: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  json_serializable: ^6.8.0
  mocktail: 1.0.3
  retrofit_generator: ^9.1.2
  spider: 4.2.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Prompt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/Prompt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Prompt-Black.ttf
          weight: 900
