/// All packages and widgets for project

/// Packages
export 'dart:async';
export 'dart:math';
export 'dart:io';
export 'package:flutter/material.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:provider/provider.dart';
export 'package:flutter_native_splash/flutter_native_splash.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:flutter/services.dart';
export 'package:mask_text_input_formatter/mask_text_input_formatter.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:dio/dio.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:flutter/foundation.dart';
export 'package:path_provider/path_provider.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_crashlytics/firebase_crashlytics.dart';
export 'package:flutter_localization/flutter_localization.dart';
export 'package:adaptive_theme/adaptive_theme.dart';
export 'package:auto_route/auto_route.dart';
export 'package:union_state/union_state.dart';
export 'package:flutter/gestures.dart';
export 'package:get_it/get_it.dart';
export 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
export 'package:easy_image_viewer/easy_image_viewer.dart';
export 'package:fluttertoast/fluttertoast.dart';

/// Project files
export 'package:everlook_mobile/source/notifications_service.dart';
export 'package:nested/nested.dart';
export 'package:everlook_mobile/data/persistence/storage/tokens_storage/auth_token_pair.dart';
export 'package:everlook_mobile/data/persistence/storage/tokens_storage/token_storage_impl.dart';
export 'package:everlook_mobile/styles/app_colors.dart';
export 'package:everlook_mobile/source/constants.dart';
export 'package:everlook_mobile/source/functions.dart';
export 'package:everlook_mobile/features/app/di/app_scope.dart';
export 'package:everlook_mobile/ui_kit/splash_screen.dart';
export 'package:everlook_mobile/styles/app_theme.dart';
export 'package:elementary/elementary.dart';
export 'package:everlook_mobile/ui_kit/colors/app_color_scheme.dart';
export 'package:everlook_mobile/ui_kit/text/app_text_scheme.dart';
export 'package:everlook_mobile/config/environment/environment.dart';
export 'package:everlook_mobile/features/app/app_main.dart';
export 'package:everlook_mobile/features/app/di/app_scope_register.dart';
export 'package:everlook_mobile/features/activities/presentation/activities_flow.dart';
export 'package:everlook_mobile/features/favorites/presentation/favorites_flow.dart';
export 'package:everlook_mobile/features/home/presentation/home_flow.dart';
export 'package:everlook_mobile/features/my_offer/presentation/my_offer_flow.dart';
export 'package:everlook_mobile/features/new_job/presentation/new_job_flow.dart';
export 'package:everlook_mobile/features/offer_request/presentation/offer_request_flow.dart';
export 'package:everlook_mobile/features/offers/presentation/offers_flow.dart';
export 'package:everlook_mobile/features/menu/presentation/menu_flow.dart';
export 'package:everlook_mobile/features/rejected_offers/presentation/rejected_offers_flow.dart';
export 'package:everlook_mobile/features/reviews/presentation/reviews_flow.dart';
export 'package:everlook_mobile/features/settings/presentation/settings_flow.dart';
export 'package:everlook_mobile/features/support/presentation/support_flow.dart';
export 'package:everlook_mobile/navigation/app_route_paths.dart';
export 'package:everlook_mobile/ui_kit/buttons/app_button.dart';
export 'package:everlook_mobile/ui_kit/text_field/app_text_field.dart';
export 'package:everlook_mobile/gen/assets.gen.dart';
export 'package:everlook_mobile/ui_kit/flutter_switch.dart';
export 'package:everlook_mobile/ui_kit/avatar_widget.dart';
export 'package:everlook_mobile/source/localizations.dart';
export 'package:everlook_mobile/ui_kit/distance_widget.dart';
export 'package:everlook_mobile/ui_kit/language_widget.dart';
export 'package:everlook_mobile/ui_kit/photo_count_widget.dart';
export 'package:everlook_mobile/ui_kit/price_range_widget.dart';
export 'package:everlook_mobile/ui_kit/rating_widget.dart';
export 'package:everlook_mobile/ui_kit/status_widget.dart';
export 'package:everlook_mobile/ui_kit/custom_appbar.dart';
export 'package:everlook_mobile/ui_kit/selectable_widget.dart';
export 'package:everlook_mobile/ui_kit/element_container.dart';
export 'package:everlook_mobile/ui_kit/image_widget.dart';
export 'package:everlook_mobile/ui_kit/circular_progress_indicator_widget.dart';

/// Models
export 'package:everlook_mobile/data/models/user_model/user_model.dart';
export 'package:everlook_mobile/data/models/item_model/item_model.dart';
export 'package:everlook_mobile/data/models/image_model/image_model.dart';
export 'package:everlook_mobile/data/models/location_model/location_model.dart';
export 'package:everlook_mobile/data/models/activity_model/activity_model.dart';
export 'package:everlook_mobile/data/models/job_model/job_model.dart';
export 'package:everlook_mobile/data/models/review_model/review_model.dart';
export 'package:everlook_mobile/data/models/video_model/video_model.dart';
export 'package:everlook_mobile/data/models/portfolio_model/portfolio_model.dart';
export 'package:everlook_mobile/data/models/avatar_model/avatar_model.dart';

/// Enum
export 'package:everlook_mobile/source/enum.dart';

/// Custom icons
export 'package:everlook_mobile/ui_kit/buttons/custom_button.dart';
export 'package:everlook_mobile/source/custom_painters.dart';

/// Repositories
export 'package:everlook_mobile/data/i_repositories/i_profile_repository.dart';
export 'package:everlook_mobile/data/repositories/profile_repository.dart';
export 'package:everlook_mobile/data/i_repositories/i_jobs_repository.dart';
export 'package:everlook_mobile/data/i_repositories/i_common_repository.dart';

/// Services
export 'package:everlook_mobile/data/services/profile_service/profile_service.dart';
export 'package:everlook_mobile/data/services/jobs_service/jobs_service.dart';
export 'package:everlook_mobile/data/services/common_service/common_service.dart';
